name: Deploy to Netlify (every branch)

on:
  push:
    branches:
      - "**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn

      - name: Build the project
        run: yarn run build
      - name: Install Netlify CLI
        run: yarn add -g netlify-cli

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"
          netlify deploy \
            --dir=dist \ # or your build output folder
            --message="Deploy from $BRANCH_NAME" \
            --prod-if-unmatched \
            --branch="$BRANCH_NAME"
